[project]
name = "kepler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "lightkurve>=2.0.0",
    "numpy>=1.20.0",
    "matplotlib>=3.4.0",
    "astropy>=5.0.0",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
]
